### ISSUE TITLE
dead loop with huge stdin input of css

### ISSUE THREAD

**Issue by ije** [esbuild/deno-esbuild#1]
When i try to build a large css file (3.6mb, tailwind.css) as **stdin** input, the build falls into an infinite loop:

```js
 const ret = await esbuild({
    stdin: {
      loader: 'css',
      sourcefile: url,
      contents: css // 3.6mb, tailwind.css
    },
    minify: true,
    write: false,
    sourcemap: false,
  })
```

use filepath works fine: 

```js
 const ret = await esbuild({
    entryPoints: ['./tailwind.css'],
    minify: true,
    write: false,
    sourcemap: false,
  })
```

__

deno 1.9.2 (release, x86_64-apple-darwin)

**Comment by evanw** [comment]
Just saw this. Sorry but the https://github.com/esbuild/deno-esbuild is just for deployments (Deno requires a GitHub repo for hosting). The esbuild repo is https://github.com/evanw/esbuild. I transferred this over to https://github.com/evanw/esbuild/issues/1219.
